In [56]:
import pandas as pd
import ast

In [4]:
track_genres = pd.read_csv('./id_genres_mmsr.tsv', sep='\t')

In [7]:
# we select 1000k randomly sampled tracks to create the pairs
len(track_genres)**2

26501904

In [11]:
total_samples = 1000000

In [58]:
track_genres['genre'] = track_genres['genre'].apply(lambda x: ast.literal_eval(str(x)))

In [12]:
import numpy as np

In [34]:
samples = set([(0, 1)])
samples.add((1, 2))

In [35]:
samples, len(samples) < total_samples

({(0, 1), (1, 2)}, True)

In [36]:
while True:
    if len(samples) > total_samples:
        break
    i, j = np.random.randint(0, len(track_genres), size=2)
    if i != j and (i, j) not in samples and (j, i) not in samples:
        samples.add((i, j))

In [37]:
i_s = [i for i, j in samples]
j_s = [j for i, j in samples]

In [59]:
i_track_genres = track_genres.loc[i_s]
i_track_genres.columns = ['i', 'i_genres']
i_track_genres = i_track_genres.reset_index(drop=True)
j_track_genres = track_genres.loc[j_s]
j_track_genres.columns = ['j', 'j_genres']
j_track_genres = j_track_genres.reset_index(drop=True)

In [60]:
i_track_genres.head(1)

                  i                                           i_genres
0  8d7H6X6duAMz3Llj  [rock, pop, power pop, alternative rock, indie...

In [61]:
dataset = i_track_genres.merge(j_track_genres, left_index=True, right_index=True)[['i', 'j', 'i_genres', 'j_genres']]

In [62]:
dataset.head(1)

,i,j,i_genres,j_genres
0,8d7H6X6duAMz3Llj,Yew4sg3Mh8KG3dXe,"[rock, pop, power pop, alternative rock, indie...","[metal, death metal, brutal death metal]"

In [63]:
dataset['is_match'] = dataset.apply(lambda row: len(set(row['i_genres']).intersection(set(row['j_genres']))) > 0, axis=1)

In [64]:
dataset.head(1)

,i,j,i_genres,j_genres,is_match
0,8d7H6X6duAMz3Llj,Yew4sg3Mh8KG3dXe,"[rock, pop, power pop, alternative rock, indie...","[metal, death metal, brutal death metal]",{}